name: "Setup Binaryen Toolkit"
description: "Setup WebAssembly Binaryen Toolkit"
branding:
  icon: download
  color: purple
inputs:
  version:
    description: "Version to Install"
    default: "latest"
runs:
  using: "composite"
  steps:
    - name: Setup Binaryen
      shell: bash
      run: |
        set -e

        VERSION="${{ inputs.version }}"
        if [ "$VERSION" = 'latest' ]; then
          VERSION=$(curl -L "https://api.github.com/repos/WebAssembly/binaryen/releases/latest" | jq -r '.tag_name')
        fi
        echo "Version: $VERSION"

        if [ "$RUNNER_ARCH" = "X64" ]; then
          ASSET="x86_64"
        elif [ "$RUNNER_ARCH" = "ARM64" ]; then
          if [ "$RUNNER_OS" = 'Linux' ]; then
            ASSET="aarch64"
          else
            ASSET="arm64"
          fi
        else
          echo "Arch: $RUNNER_ARCH"
          exit 1
        fi
        echo "Arch: $ASSET"

        if [ "$RUNNER_OS" = 'Linux' ]; then
          ASSET=".*$ASSET.*linux.*\\\\.tar\\\\.gz$"
        elif [ "$RUNNER_OS" = 'macOS' ]; then
          ASSET=".*$ASSET.*macos.*\\\\.tar\\\\.gz$"
        elif [ "$RUNNER_OS" = 'Windows' ]; then
          ASSET=".*$ASSET.*windows.*\\\\.tar\\\\.gz$"
        else
          echo "Arch: $RUNNER_OS"
          exit 1
        fi
        echo "Test: $ASSET"

        ASSET=$(curl -L "https://api.github.com/repos/WebAssembly/binaryen/releases/tags/$VERSION" | jq -r ".assets[].name | select(test(\"$ASSET\"))")
        echo "Asset: $ASSET"

        mkdir binaryen
        curl -L "https://github.com/WebAssembly/binaryen/releases/download/$VERSION/$ASSET" | tar -xzC binaryen --strip-components=1
        ls binaryen/bin
        echo "$(pwd -W 2>/dev/null || pwd)/binaryen/bin" >> $GITHUB_PATH
