name: Test
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'
jobs:
  test-build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        version: [canary, latest, version_124]
    steps:
      - uses: actions/checkout@v7
      - name: Test Build
        uses: ./
        env:
          GH_TOKEN: ${{ github.token }}
        with:
          version: ${{ matrix.version }}
          cache: 'false'
      - name: Validate Success
        run: wasm-opt --version
  test-cache:
    needs: test-build
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        version: [canary, latest, version_124]
    steps:
      - uses: actions/checkout@v7
      - name: Test Cache
        uses: ./
        env:
          GH_TOKEN: ${{ github.token }}
        with:
          version: ${{ matrix.version }}
          cache: 'true'
      - name: Validate Success
        run: wasm-opt --version
